// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations run DDL, which the pooler (DATABASE_URL) doesn't support —
    // the CLI needs the direct connection. The app's runtime client is
    // unaffected: src/lib/prisma.ts reads DATABASE_URL independently via
    // the driver adapter.
    url: process.env["DIRECT_URL"],
  },
});
